sudo: required
addons:
  apt:
    sources:
    - ubuntu-xenial
    - sourceline: 'ppa:neurobin/ppa'
    packages:
    - build-essential
    - shc
before_script:
    - sudo apt-get update
script:
    - make
    - make appimage
