sudo: required
addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu xenial main restricted multiverse universe'
    packages:
    - devscripts
    - fakeroot
    - debhelper

before_script:
    - sudo apt update

script:
    - bash utils/standalone.sh
    - bash utils/appimage.sh
    - dpkg-buildpackage -uc -us

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh bin/halium-install-x86_64.AppImage bin/halium-install-standalone.sh ../halium-install_*_all.deb

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
