sudo: required
addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu xenial main restricted multiverse universe'
    - sourceline: 'ppa:neurobin/ppa'
    packages:
    - build-essential
    - shc
script:
    - make
    - make appimage
